{
  "compute_environment": "LOCAL_MACHINE",
  "debug": false,
  "deepspeed_config":{
    "zero_stage": 2,
    "gradient_clipping": 1.0
  },
  "distributed_type": "DEEPSPEED",
  "machine_rank": 0,
  "main_training_function": "main",
  "mixed_precision": "no",
  "num_machines": 1,
  "num_processes": 2,
  "rdzv_backend": "static",
  "same_network": false,
  "tpu_use_cluster": false,
  "tpu_use_sudo": false,
  "use_cpu": false
}